basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a sample API using net/http with Swagger.
  title: Example API
  version: "1.0"
paths:
  /sample:
    get:
      description: Returns a JSON response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a sample response
swagger: "2.0"
